### ISSUE TITLE
Ignore case

### ISSUE THREAD

**Issue by goldsheetbob** [AlbertWiersch/html-validator#1]
Sorry to bother you, but I was unable to find solution.

Yahoo recently changed the way they do quotes

lowercase used to work: https://finance.yahoo.com/quote/zon,v
but now they insist on uppercase: https://finance.yahoo.com/quote/ZON.V

Instead of changing all my urls, I would like validator to ignore case

Thank you in advance for any help you can provide

**Comment by AlbertWiersch** [comment]
Hello,

Could the issue be that in the lowercase link there is a comma instead of a period? i.e. "zon,v" instead of "zon.v"?

**Comment by goldsheetbob** [comment]
As my luck would have it, I made a typo in the message, (sorry)
All of the 1000+ yahoo quote links on my website https://goldsheetlinks.com/ previously validated correctly 
Yahoo must have changed something requiring uppercase instead of lowercase required.
Not an issue with CSE (love it!) , just wish I could ignore these error messages.

![yahoo](https://github.com/AlbertWiersch/html-validator/assets/171278336/77d969ac-be31-405d-a9bc-4421cb4c021c)

**Comment by AlbertWiersch** [comment]
Hello,

It sounds like Yahoo changed their servers to respond different to the requests that **CSS HTML Validator** uses for link checking.

**CSS HTML Validator** has 'link filters' that you can use to ignore or not check matching links. Here is more information:
https://www.htmlvalidator.com/current/docs/engine_link_filters_node.htm

For example, you could set 'These links are always good' to something like 'https://finance.yahoo.com/quote/*'.

![image](https://github.com/AlbertWiersch/html-validator/assets/7662186/1d1f6001-d0bc-4ae4-8010-fea72f6e36a5)

I hope this helps. Please let me know if you have any more questions.

**Comment by goldsheetbob** [comment]
Thank you for your help.
